#serial_port : "/dev/ttyACM0" # Udev rule to make a virtual port that's associated to specific hw
baudrate : 115200
cmd_vel_topic: "/cmd_vel_roboteq"

closed_loop: true

# For differential drive control (dual channel controller)
diff_drive_mode: true
wheel_circumference: 0.6377 # [m]
track_width: .493 # [m]
max_rpm: 3000 # [rpm]
encoder_resolution: 1024

# For querying data from the motor controller
# testing
frequency: 50   #higher frequency (value is in ms)
query:
  motor_amps : ?A
  motor_command : ?M
  hall_count : ?Cb
  hall_speed : ?BS
  volts : ?V
  battery_amps : ?BA
  # power : ?P          
  fault_flag : ?FF
  encoder_count : ?C
  encoder_speed : ?S
  # DigIn in 10 bit but sent as decimal. 8 pins.
  # DigOut in 10 but but sent as decimal. 8 pins.
  dig_in : ?D 1
  dig_out : ?Do
